//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dao
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_log
    {
        public int Id { get; set; }
        public string DiaMes { get; set; }
        public string Hora { get; set; }
        public string Ocorrencia { get; set; }
        public string Descrição { get; set; }
    }
}
